### ISSUE TITLE
Pi Cluster Hat

### ISSUE THREAD

**Issue by robertfullagar** [virtualabs/btlejack#69]
Hi 

Great Tool..love it..

What changes did you make to the pi cluster hat so you could get 3 x BBC Micro's to work on it? 

Regards

Robert

**Comment by virtualabs** [comment]
I removed the transistors driving power for each of the 4 male USB connectors that connect to the Pis and soldered a piece of wire on each in order to provide continuous power. I did that on a ClusterHat version 2.2, I'm not sure it will work with the latest version. Anyways, the main idea is to keep the Pis USB ports powered on when the main USB connector is plugged to your computer.
